apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-aaa
spec:
  replicas: 6
  selector:
    matchLabels:
      app: nginx-aaa
  template:
    metadata:
      labels:
        app: nginx-aaa
    spec:
      containers:
      - name: nginx-aaa
        image: nginx
        resources:
          limits:
            memory: "64Mi"
            cpu: "250m"
        ports:
        - containerPort: 80
      affinity:
        podAntiAffinity:          
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - "nginx-bbb"
                      - "nginx-aaa"
              topologyKey: prioridade
        
